---
apiVersion: v1
kind: Pod
metadata:
  name: simple-web-service
  labels:
    app: simple-web-service

spec:
  containers: 
  - name: simple-web-service
    image: jasongvn/hihi
    ports:
      - containerPort: 8080